// receiving-data.js
// Centralized frontend data for the Razor receiving demo.
// 339 commodities + 8 packaging types + 13 workflow steps.

const COMMODITIES = [
  { id: 659, name: "A/C Unit" },
  { id: 559, name: "Absolyte" },
  { id: 493, name: "Ac Compressor" },
  { id: 446, name: "Adapter w/o Wire" },
  { id: 560, name: "Adapters" },
  { id: 387, name: "Air Conditioner" },
  { id: 561, name: "Alkaline" },
  { id: 120, name: "All In One" },
  { id: 413, name: "All in One - C2D" },
  { id: 414, name: "All in One - iSeries" },
  { id: 624, name: "ALL IN ONE SCRAP" },
  { id: 562, name: "All-in-one Computers" },
  { id: 490, name: "Alternator" },
  { id: 210, name: "Aluminum" },
  { id: 539, name: "aluminum can" },
  { id: 528, name: "aluminum wire strip" },
  { id: 563, name: "Analog electric motors" },
  { id: 616, name: "apc sealed non-spillable lead acid" },
  { id: 331, name: "APC Unit" },
  { id: 557, name: "apple adapter with wire" },
  { id: 525, name: "apple mouse" },
  { id: 613, name: "ATM machine" },
  { id: 623, name: "AUDIO SYSTEM" },
  { id: 518, name: "Backage wire copper" },
  { id: 432, name: "Bag - Laptop" },
  { id: 3, name: "Bags - SCRAP" },
  { id: 449, name: "Ballasts" },
  { id: 495, name: "BAR CODE SCANNER" },
  { id: 5, name: "Battery - Dry cell Alkaline" },
  { id: 441, name: "Battery - Lead Acid" },
  { id: 6, name: "Battery - LiON" },
  { id: 10, name: "Battery - NiCAD" },
  { id: 630, name: "BATTERY BUTTON" },
  { id: 614, name: "BLACK BOX" },
  { id: 497, name: "blower motor" },
  { id: 492, name: "Brake Rotors" },
  { id: 440, name: "Cable - Apple" },
  { id: 21, name: "Cable - Power" },
  { id: 18, name: "Cable - VGA" },
  { id: 564, name: "Cable boxes" },
  { id: 556, name: "cable wire" },
  { id: 391, name: "Camera" },
  { id: 565, name: "Capacitors" },
  { id: 374, name: "Cardboard" },
  { id: 648, name: "CAT5 wire" },
  { id: 483, name: "cataytic converter" },
  { id: 566, name: "CD-ROM/optical drives" },
  { id: 451, name: "CD/DVD" },
  { id: 567, name: "Cell phones" },
  { id: 244, name: "Cellphone" },
  { id: 670, name: "Charging Cart" },
  { id: 612, name: "Charging Carts" },
  { id: 640, name: "CHOP COPPER" },
  { id: 655, name: "christmas wire" },
  { id: 510, name: "CHROMEBOOK" },
  { id: 617, name: "Chromebook 13\" good screen" },
  { id: 618, name: "chromebook 14\" good screen" },
  { id: 641, name: "chromebook bad screen" },
  { id: 473, name: "Chromebook Board" },
  { id: 620, name: "chromebook good screen 360 & Touch screen" },
  { id: 633, name: "CHROMEBOOK GOOD SCREEN MIX SIZE" },
  { id: 524, name: "CHROMEBOOK MANAGED" },
  { id: 521, name: "CHROMEBOOK SCARP" },
  { id: 649, name: "chromebook touch screen scrap" },
  { id: 479, name: "chromebook-with board good screen" },
  { id: 419, name: "Chromebooks - Audited" },
  { id: 420, name: "Chromebooks - Tested and Working" },
  { id: 455, name: "Chromebooks - with board no screen/broken" },
  { id: 39, name: "Circuit Boards - Hard Drive Boards" },
  { id: 40, name: "Circuit Boards - HG" },
  { id: 41, name: "Circuit Boards - LG" },
  { id: 50, name: "Circuit Boards - Mid-grade" },
  { id: 49, name: "Circuit Boards - PCI/Finger" },
  { id: 51, name: "Circuit Boards - Printer" },
  { id: 67, name: "Circuit Boards - Server, Network, Communication" },
  { id: 654, name: "complete desktop" },
  { id: 568, name: "Compressors/sealed units" },
  { id: 90, name: "Connectors - Pins" },
  { id: 527, name: "cooper wire strip" },
  { id: 102, name: "Copier - Disposal" },
  { id: 418, name: "Copier - Downstream Disposal" },
  { id: 634, name: "COPPER" },
  { id: 549, name: "COPPER HEATSINK" },
  { id: 540, name: "COPPER TRANSFORMER" },
  { id: 439, name: "Copper Wire" },
  { id: 516, name: "copper with metal mix" },
  { id: 637, name: "CPU" },
  { id: 178, name: "CPU Fan" },
  { id: 615, name: "CRD RECYCLING FOR SHIBL" },
  { id: 430, name: "Credit Card Machine" },
  { id: 508, name: "CRT COOPER WIRE" },
  { id: 108, name: "CRT Monitor - DSV" },
  { id: 569, name: "CRT monitors & televisions" },
  { id: 110, name: "CRT Monitors - Disposal" },
  { id: 570, name: "CRT/monitor boards" },
  { id: 476, name: "Cut Chip" },
  { id: 410, name: "Deskop - iSeries No Power" },
  { id: 608, name: "desktop" },
  { id: 73, name: "Desktop - C2D DDR2" },
  { id: 84, name: "Desktop - C2D DDR3" },
  { id: 408, name: "Desktop - iSeries 5th Gen & up" },
  { id: 80, name: "Desktop - P4" },
  { id: 534, name: "DESKTOP AMD" },
  { id: 598, name: "desktop amd 2" },
  { id: 632, name: "DESKTOP HIGH CONFIGARATION" },
  { id: 530, name: "DESKTOP I SERIES 6TH GEN" },
  { id: 531, name: "DESKTOP I SERIES 7TH GEN" },
  { id: 529, name: "DESKTOP I SERIES 9 TH GEN" },
  { id: 621, name: "DESKTOP I-SERIES BONE BOX" },
  { id: 536, name: "DESKTOP I7 SERIES" },
  { id: 610, name: "DESKTOP ISERIES I3 SERIES" },
  { id: 609, name: "DESKTOP ISERIES I5 SERIES" },
  { id: 512, name: "DESKTOP MINI" },
  { id: 167, name: "desktop power supply  with wire" },
  { id: 409, name: "Desktop Scrap" },
  { id: 484, name: "DESKTOP-4TH GEN I-SERIES" },
  { id: 402, name: "Desktops- Audited" },
  { id: 571, name: "Digital electric motors" },
  { id: 572, name: "Disc arrays" },
  { id: 157, name: "Docking station" },
  { id: 573, name: "Docking stations" },
  { id: 162, name: "DVD Drive" },
  { id: 433, name: "DVD Player" },
  { id: 657, name: "DVR" },
  { id: 541, name: "ELECTRIC MOTOR" },
  { id: 574, name: "Electric motors" },
  { id: 548, name: "electric scrap" },
  { id: 396, name: "Electronic Scrap - TO BE SORTED" },
  { id: 551, name: "End of connector mix" },
  { id: 499, name: "EXHAUST SOLENOID" },
  { id: 575, name: "Fans" },
  { id: 576, name: "Fingerboards" },
  { id: 203, name: "Floppy Disk" },
  { id: 554, name: "floppy disk drive" },
  { id: 526, name: "Grind cooper wire" },
  { id: 635, name: "grind plastic" },
  { id: 443, name: "Hard Drive - Caddy" },
  { id: 175, name: "Hard Drive - crushed" },
  { id: 170, name: "Hard Drive - Crushed w/o Board" },
  { id: 171, name: "Hard Drive - Shredded" },
  { id: 577, name: "Hard drive boards" },
  { id: 523, name: "Hard Drive ssd chip" },
  { id: 578, name: "Hard Drives - Audited" },
  { id: 517, name: "Harness wire" },
  { id: 448, name: "Headphone" },
  { id: 579, name: "Heat sinks" },
  { id: 191, name: "Heatsink" },
  { id: 660, name: "Hover Cam" },
  { id: 478, name: "I- pad Cover" },
  { id: 646, name: "I-Pad" },
  { id: 504, name: "I-PAD COVER" },
  { id: 636, name: "IMAC" },
  { id: 405, name: "iMac - Audited" },
  { id: 422, name: "iMac - Silver C2D" },
  { id: 423, name: "iMac - Silver iSeries" },
  { id: 421, name: "iMac - White" },
  { id: 544, name: "IMAC SCRAP" },
  { id: 666, name: "iPad" },
  { id: 416, name: "iPad - Audited" },
  { id: 445, name: "iPad - Broken" },
  { id: 424, name: "iPad - Tested" },
  { id: 519, name: "IPAD CASE" },
  { id: 226, name: "Iron Sheet" },
  { id: 458, name: "Keyboard - Apple" },
  { id: 199, name: "Keyboards - PS2" },
  { id: 200, name: "Keyboards - USB" },
  { id: 580, name: "Keyboards/mice" },
  { id: 243, name: "Landline Phone" },
  { id: 469, name: "Laptop - C2D good screen, parts missing" },
  { id: 411, name: "Laptop - C2D TESTED" },
  { id: 509, name: "laptop - i series 4th gen" },
  { id: 412, name: "Laptop - iSeries" },
  { id: 459, name: "Laptop - Iseries non working" },
  { id: 76, name: "Laptop - Scrap" },
  { id: 627, name: "LAPTOP BAD SCREEN C2D" },
  { id: 542, name: "LAPTOP BATTERY LION" },
  { id: 475, name: "Laptop Board" },
  { id: 653, name: "Mix Electronics" },
  { id: 611, name: "mix scrap" },
  { id: 500, name: "MIX SIZE GOOD LAPTOP SCREEN" },
  { id: 590, name: "Motherboards" },
  { id: 488, name: "MOTOR" },
  { id: 390, name: "Mouse - PS2" },
  { id: 425, name: "Mouse - USB" },
  { id: 235, name: "Network Equipment" },
  { id: 238, name: "Network Equipment - Switches" },
  { id: 591, name: "Networking" },
  { id: 470, name: "New box items misc" },
  { id: 485, name: "new cartridge" },
  { id: 592, name: "Nickel metal-hydride (NiMH)" },
  { id: 593, name: "Nickel-cadmium (NiCad)" },
  { id: 537, name: "nylon plastic" },
  { id: 466, name: "Oven" },
  { id: 538, name: "paper" },
  { id: 474, name: "Parts - Laptop" },
  { id: 594, name: "Phones" },
  { id: 249, name: "Plastic - ABS Desktop" },
  { id: 457, name: "Plastic - ABS LCD" },
  { id: 456, name: "Plastic - ABS LCD TV" },
  { id: 250, name: "Plastic - ABS Mix" },
  { id: 667, name: "Plotter/Printer" },
  { id: 595, name: "Power boards" },
  { id: 472, name: "power Strip without wire" },
  { id: 596, name: "Power strips" },
  { id: 597, name: "Power supplies" },
  { id: 305, name: "Power Supplies - with wire" },
  { id: 502, name: "Power Supplies - without wire" },
  { id: 259, name: "Printer - Disposal" },
  { id: 289, name: "Printer - Downstream" },
  { id: 442, name: "Printer - NEW" },
  { id: 555, name: "printer motor" },
  { id: 381, name: "Processor - Clean Pulled" },
  { id: 552, name: "processor slot" },
  { id: 599, name: "Processors" },
  { id: 292, name: "Processors - Ceramic" },
  { id: 356, name: "Projector" },
  { id: 447, name: "projector - scrap" },
  { id: 427, name: "Projector - with bulbs" },
  { id: 513, name: "PROJECTOR BULB" },
  { id: 431, name: "Radio" },
  { id: 644, name: "ram" },
  { id: 52, name: "Ram - Gold" },
  { id: 404, name: "Ram - Heat Shielded" },
  { id: 403, name: "Ram - Silver" },
  { id: 429, name: "Ram - Tested" },
  { id: 464, name: "Refrigerator" },
  { id: 668, name: "REMOTE" },
  { id: 547, name: "remote circuit board-MIX GRADE" },
  { id: 392, name: "Remote Control" },
  { id: 553, name: "sata wire" },
  { id: 600, name: "Server motherboards" },
  { id: 558, name: "SERVER POWER SUPPLY" },
  { id: 601, name: "Servers" },
  { id: 369, name: "Servers - Audited" },
  { id: 428, name: "Servers - Processed" },
  { id: 515, name: "SHREDDED CIRCUIT BOARD" },
  { id: 454, name: "Small Appliance" },
  { id: 656, name: "Smart Board LED" },
  { id: 471, name: "Smartboards" },
  { id: 642, name: "SOLER PANEL" },
  { id: 313, name: "Speaker" },
  { id: 491, name: "Starter" },
  { id: 602, name: "Steel/Iron" },
  { id: 489, name: "Steering Column Shaft" },
  { id: 194, name: "Stereo Equipment" },
  { id: 465, name: "Stove" },
  { id: 546, name: "switch circuit board-HG" },
  { id: 665, name: "Tablet" },
  { id: 415, name: "Tablet - Audited" },
  { id: 503, name: "Tablet - BROKEN" },
  { id: 426, name: "Tablet - Tested" },
  { id: 506, name: "TABLET AS IS" },
  { id: 639, name: "tablet scrap" },
  { id: 450, name: "Tape" },
  { id: 603, name: "Telecom boards" },
  { id: 535, name: "TELIPHONE CIRCUIT BOARD HG" },
  { id: 604, name: "Toner cartridges, tape drives, media" },
  { id: 195, name: "Toner/Ink Cartridge" },
  { id: 664, name: "TOOL BATTERY" },
  { id: 317, name: "Transformer - Adapter" },
  { id: 326, name: "Transformers" },
  { id: 155, name: "TV - LCD Disposal" },
  { id: 118, name: "TV - Tube/Flat Screen Disposal" },
  { id: 417, name: "TV -TUBE  Downstream Disposal" },
  { id: 605, name: "UPS" },
  { id: 481, name: "UPS/APC unit" },
  { id: 651, name: "VCR" },
  { id: 638, name: "WALKI TALKI" },
  { id: 467, name: "Washer & Dryer" },
  { id: 545, name: "waste to landfill" },
  { id: 522, name: "Wifi Card" },
  { id: 652, name: "Wifi Router" },
  { id: 606, name: "Wire" },
  { id: 336, name: "Wire - mix cut" },
  { id: 434, name: "Wire - NEW" },
  { id: 494, name: "Wire Harness" },
  { id: 482, name: "Wiring Harness" },
  { id: 607, name: "Yokes" }
];

// Packaging types from Razor.
// weight is the default tare associated with the packaging type.

const PACKAGING_TYPES = [
  { id: 18, name: "Pallet", weight: 45 },
  { id: 19, name: "Gaylord", weight: 70 },
  { id: 20, name: "Unit", weight: 0 },
  { id: 21, name: "Box", weight: 0 },
  { id: 22, name: "Loose", weight: 0 },
  { id: 23, name: "Cage", weight: 180 },
  { id: 24, name: "40 yard roll-off container", weight: 32200 },
  { id: 25, name: "Double Gaylord", weight: 140 }
];


// Workflow steps from Razor.

const WORKFLOW_STEPS = [
  { businessUnitId: 1, id: 10, isFinal: false, name: "Audit" },
  { businessUnitId: 1, id: 9, isFinal: false, name: "Consumed" },
  { businessUnitId: 1, id: 3, isFinal: false, name: "Data Destruction" },
  { businessUnitId: 1, id: 14, isFinal: false, name: "Dismantle" },
  { businessUnitId: 1, id: 4, isFinal: false, name: "Final" },
  { businessUnitId: 1, id: 13, isFinal: false, name: "Finished Goods - Ready for Shipment" },
  { businessUnitId: 1, id: 11, isFinal: false, name: "ITAD" },
  { businessUnitId: 1, id: 8, isFinal: false, name: "Processed" },
  { businessUnitId: 3, id: 20, isFinal: false, name: "Processed & Audit" },
  { businessUnitId: 1, id: 18, isFinal: false, name: "Scrap" },
  { businessUnitId: 1, id: 1, isFinal: false, name: "Sort" },
  { businessUnitId: 1, id: 5, isFinal: false, name: "Testing" },
  { businessUnitId: 1, id: 16, isFinal: false, name: "Work in progress" }
];


// Default selections for the receiving demo.

const RECEIVING_DEFAULTS = {
  commodityId: 653,          // Mix Electronics
  packagingTypeId: 19,       // Gaylord
  weightTare: 70,            // Gaylord tare
  workflowStepId: 9          // Consumed
};